apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamestoreclient-deployment
  labels:
    app: gamestoreclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamestoreclient
  template:
    metadata:
      labels:
        app: gamestoreclient
    spec:
      containers:
        - name: gamestoreclient
          image: gamestoreacr.azurecr.io/gamestoreclient:v1
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: acr-secret
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: gamestoreAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: gamestoreapi-configmap
                    key: gamestoreapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gamestoreclient-service
spec:
  type: LoadBalancer
  selector:
    app: gamestoreclient
  ports:
    - protocol: TCP
      port: 80